apiVersion: v1
kind: Service
metadata:
  name: my-service-pokemonfinder
  namespace: aymeric
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"80":{"name": "my-service-pokemonfinder"}}}'
spec:
  selector:
    app.kubernetes.io/aymeric: pokemon-finder-aymeric
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
