name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to v4 to ensure Node.js 20 compatibility

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3  # Updated to v3 to ensure Node.js 20 compatibility

    - name: Authenticate to Google Artifact Registry
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_Auth }}
      run: |
        echo ${{ secrets.GCP_Auth }} | base64 --decode > key.json
        cat key.json | docker login -u _json_key_base64 --password-stdin https://europe-west9-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build -t monapp:latest .

    - name: Tag Docker image for Google Artifact Registry
      run: |
        docker tag monapp:latest europe-west9-docker.pkg.dev/infal-devops-sysops/student-aymeric/monapp:latest

    - name: Push Docker image to Google Artifact Registry
      run: |
        docker push europe-west9-docker.pkg.dev/infal-devops-sysops/student-aymeric/monapp:latest
