name: CI/CD for Pokemon Finder

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx@v2
      - name: Login to GCP registry
        run: |
          echo "${{ secrets.GCP_AUTH }}" | docker login -u _json_key_base64 --password-stdin https://europe-west9-docker.pkg.dev
      - name: Build and push
        run: |
          docker buildx build --platform linux/amd64 --tag europe-west9-docker.pkg.dev/infal-devops-sysops/student-aymeric/pokemon-finder .
          docker push europe-west9-docker.pkg.dev/infal-devops-sysops/student-aymeric/pokemon-finder