name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Authenticate to Google Artifact Registry
      env:
        GCP_AUTH: ${{ secrets.GCP_Auth }}
      run: |
        echo $GCP_AUTH | base64 --decode > /tmp/key.json
        gcloud auth activate-service-account --key-file=/tmp/key.json
        cat /tmp/key.json | docker login -u _json_key_base64 --password-stdin https://europe-west9-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build -t monapp:latest .

    - name: Tag Docker image for Google Artifact Registry
      run: |
        docker tag monapp:latest europe-west9-docker.pkg.dev/infal-devops-sysops/student-aymeric/monapp:latest

    - name: Push Docker image to Google Artifact Registry
      run: |
        docker push europe-west9-docker.pkg.dev/infal-devops-sysops/student-aymeric/monapp:latest
